const services = [
  { number: "01", title: "Механизированная штукатурка", text: "Подготавливаем стены и откосы под дальнейшую отделку. Работаем с квартирами, домами и коммерческими помещениями.", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=85" },
  { number: "02", title: "Механизированная стяжка пола", text: "Делаем прочное и ровное основание под плитку, ламинат, кварцвинил и другие покрытия.", image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85" },
];

export default function Home() {
  return <main>
    <section className="hero" id="top">
      <nav className="nav container" aria-label="Основная навигация"><a className="brand" href="#top" aria-label="Ровная Основа — на главную">РОВНАЯ<br />ОСНОВА<span>•</span></a><a className="nav-link" href="#services">Услуги</a><a className="nav-link" href="#process">Как работаем</a><a className="nav-cta" href="tel:+79878017549">Позвонить</a></nav>
      <div className="hero-grid container"><div className="hero-copy"><p className="eyebrow">Механизированная штукатурка · Стяжка пола</p><h1>Геометрия<br />вашего ремонта.</h1><p className="lead">Выравниваем стены и пол так, чтобы следующий этап ремонта начинался спокойно и без переделок.</p><div className="hero-actions"><a className="button" href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Написать Евгению <span>↗</span></a><a className="text-link" href="tel:+79878017549">+7 987 801-75-49</a></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1500&q=90" alt="Строительные работы на объекте" /><p className="visual-label">Квартира · Дом · Коммерческое помещение</p></div></div>
      <div className="hero-foot container"><span>ТОЛЬКО НУЖНЫЕ РАБОТЫ</span><span>ОСТАЛЬНОЕ — ПО ЗАПРОСУ</span></div>
    </section>
    <section className="services section container" id="services"><p className="eyebrow">Основные услуги</p><div className="section-heading"><h2>Делаем основу<br />ремонта правильно.</h2><p>Фокусируемся на двух главных этапах. Другие строительные работы выполняем по запросу.</p></div><div className="service-grid">{services.map((service) => <article className="service" key={service.number}><img src={service.image} alt={service.title} /><div className="service-info"><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.text}</p></div></article>)}</div></section>
    <section className="principles" id="process"><div className="container principles-grid"><p className="eyebrow">Как всё происходит</p><div><h2>Понятно<br />с первого звонка.</h2><div className="principle-items"><p><b>01 · Обсуждаем объект</b><span>Пишите Евгению в Telegram или звоните. Уточняем задачу и исходные данные.</span></p><p><b>02 · Согласовываем работы</b><span>Определяем объём, последовательность и удобное время для старта.</span></p><p><b>03 · Выполняем аккуратно</b><span>Готовим поверхности и сдаём понятный результат для следующего этапа ремонта.</span></p></div></div></div></section>
    <section className="contact section container" id="contact"><div><p className="eyebrow">Рассчитаем ваш объект</p><h2>Покажите<br />план или фото.</h2><p className="contact-note">Напишите в Telegram: можно отправить план, фото помещения или просто описать задачу. Евгений ответит лично.</p></div><div className="contact-card"><p>Связаться с мастером</p><h3>Евгений</h3><a className="phone" href="tel:+79878017549">+7 987 801-75-49</a><a className="button" href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Написать в Telegram <span>↗</span></a><small>Механизированная штукатурка и стяжка пола</small></div></section>
    <footer className="footer container"><a className="brand" href="#top">РОВНАЯ ОСНОВА<span>•</span></a><p>Механизированная штукатурка и стяжка пола</p><a href="tel:+79878017549">Позвонить</a></footer>
  </main>;
}
