import { PlasterBenefits } from "./components/PlasterBenefits";

const services = [
  { number: "01", title: "Механизированная штукатурка стен", text: "Стены и откосы под дальнейшую отделку: от подготовки основания и грунтования до глянцевания, первичной шлифовки и проверки правилом.", image: "/works/make-the-base.jpg" },
  { number: "02", title: "Механизированная стяжка пола", text: "Ровное и прочное основание под плитку, ламинат, кварцвинил и другие покрытия. Состав работ определяется после замера.", image: "/works/mechanized-screed.jpg" },
  { number: "03", title: "Установка Маяков", text: "Выставляем маяки с помощью 3D-лазерного нивелира. Это задаёт точную плоскость и помогает получить ровную основу стен.", image: "/works/laser-beacons.jpg" },
];

const portfolio = Array.from({ length: 15 }, (_, index) => ({ src: `/works/object-${String(index + 1).padStart(2, "0")}.jpg`, alt: `Реальный частный объект — этап работ ${index + 1}` }));
const materialGroups = [["Гипсовые смеси", "Knauf MP-75", "Волма Гипс Актив Экстра"], ["Цементно-песчаные", "Vetonit TT30 Lite", "Vetonit TT40"], ["Подготовка основания", "Грунтовка Knauf Mittel Grund"]];
const materialCards = [
  { image: "/works/material-knauf-mp75.png", alt: "Knauf MP 75 — гипсовая штукатурка для машинного нанесения", title: "Knauf MP 75", text: "Гипсовая смесь для механизированной штукатурки стен и потолков в сухих помещениях." },
  { image: "/works/material-volma.png", alt: "Волма Гипс-Актив Экстра — гипсовая штукатурка", title: "Волма Гипс-Актив Экстра", text: "Трещиностойкая гипсовая смесь для быстрого и ровного выравнивания." },
  { image: "/works/material-mittelgrund.png", alt: "Knauf Mittelgrund — грунтовка для подготовки основания", title: "Knauf Mittelgrund", text: "Грунтовка для подготовки основания и надёжного сцепления штукатурки со стеной." },
];

const materialCarouselScript = `(() => {
  const setup = () => {
    const carousel = document.querySelector('[data-material-carousel]');
    const button = document.querySelector('[data-material-next]');
    const status = document.querySelector('[data-material-status]');
    if (!carousel || !button || !status) return;
    const cards = Array.from(carousel.querySelectorAll('.material-card'));
    let active = 0;
    let frame;
    const highlight = (index) => {
      const card = cards[index];
      card.classList.remove('is-pulsing');
      void card.offsetWidth;
      card.classList.add('is-pulsing');
    };
    const update = () => {
      const center = carousel.scrollLeft + carousel.clientWidth / 2;
      active = cards.reduce((closest, card, index) => Math.abs(card.offsetLeft + card.offsetWidth / 2 - center) < Math.abs(cards[closest].offsetLeft + cards[closest].offsetWidth / 2 - center) ? index : closest, active);
      cards.forEach((card, index) => card.classList.toggle('is-active', index === active));
      status.textContent = 'Материал ' + String(active + 1).padStart(2, '0') + ' / ' + String(cards.length).padStart(2, '0');
      button.setAttribute('aria-label', 'Показать материал ' + String((active + 1) % cards.length + 1));
    };
    carousel.addEventListener('scroll', () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(update); }, { passive: true });
    button.addEventListener('click', () => {
      const next = (active + 1) % cards.length;
      carousel.scrollTo({ left: cards[next].offsetLeft - 1, behavior: 'smooth' });
      highlight(next);
    });
    update();
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', setup); else setup();
})();`;

export default function Home() {
  return <main>
    <section className="hero" id="top">
      <nav className="nav container" aria-label="Основная навигация"><a className="brand" href="#top" aria-label="Ровная Основа — на главную">РОВНАЯ<br />ОСНОВА<span>•</span></a><div className="nav-links"><a href="#services">Услуги</a><a href="#advantages">Условия</a><a href="#process">Как работаем</a><a href="#portfolio">Работы</a></div><a className="nav-cta" href="#contact">Рассчитать объект</a><details className="nav-menu"><summary aria-label="Открыть меню"><i /><i /><i /></summary><div><a href="#services">Услуги</a><a href="#advantages">Условия</a><a href="#process">Как работаем</a><a href="#portfolio">Работы</a><a href="#faq">Вопросы</a><a href="#contact">Связаться</a></div></details></nav>
      <div className="hero-grid container"><div className="hero-copy"><p className="eyebrow">Энгельс · Саратов · область</p><h1>Ровная Основа<br/>стены и пола —<br/>идеальный старт для вашего ремонта.</h1><p className="lead">Предлагаем механизированную (машинную) штукатурку стен, потолков и откосов в квартирах, частных домах, коммерческих помещениях и новостройках. Также выполняем механизированную стяжку пола.</p><p className="hero-proof"><span>✓</span> Работаем без предоплаты</p><div className="hero-actions"><a className="button" href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Написать Евгению<span>↗</span></a><a className="text-link" href="tel:+79878017549">+7 987 801-75-49</a></div></div><div className="hero-visual"><img src="/works/many-corners.jpg" alt="Штукатурка стен и углов в частном доме" /><p className="visual-label">Реальный объект · частный дом</p></div></div>
      <div className="hero-foot container"><span>ЗВОНКИ ЕЖЕДНЕВНО · 8:00–22:00</span><span>РАБОТАЕМ ПО ДОГОВОРУ ПОДРЯДА</span></div>
    </section>
    <section className="facts"><div className="container facts-grid"><p><b>от 70 м²</b><span>минимальный объём работ</span></p><p><b>3–8 дней</b><span>средний срок на объект</span></p><p><b>24 часа</b><span>бесплатный замер и смета</span></p><p><b>1 год</b><span>гарантия по договорённости</span></p></div></section>
    <section className="services section container" id="services"><p className="eyebrow">Основные услуги</p><div className="section-heading"><h2>Делаем основу<br />дома правильно.</h2><p>Фокусируемся на двух главных этапах. Дополнительные строительные работы обсуждаем отдельно — под задачу конкретного объекта.</p></div><div className="service-grid">{services.map((service) => <article className="service" key={service.number}><img src={service.image} alt={service.title} /><div className="service-info"><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.text}</p></div></article>)}</div></section>
    <PlasterBenefits />
    <section className="terms section" id="advantages"><div className="container"><p className="eyebrow">Честные условия</p><div className="terms-heading"><h2>Сначала материал<br />на объекте. Потом оплата.</h2><p>Организуем логистику и работаем со своим материалом. Материалы оплачиваются после фактической доставки. Можно рассчитать работы и отдельно — без материала.</p></div><div className="terms-grid"><article><span>В ТЕЧЕНИЕ 24 ЧАСОВ</span><h3>Бесплатный замер</h3><p>Выезжаем в Энгельс, Саратов и область. Смету по работам озвучиваем сразу на замере.</p></article><article className="featured"><span>ГЛАВНОЕ УСЛОВИЕ</span><h3>Материалы уже на объекте</h3><p>Сначала вы видите доставленный материал. Только после этого оплачиваете его стоимость.</p></article><article><span>БЕЗ СКРЫТЫХ ДОПЛАТ</span><h3>Понятная смета</h3><p>Объём, состав работ и стоимость согласовываем до старта. Никакого скрытого ценообразования.</p></article></div></div></section>
    <section className="estimate"><div className="container estimate-card"><div><p className="eyebrow">Без цены «вслепую»</p><h2>Сначала замер.<br />Потом точная смета.</h2></div><div className="estimate-copy"><p>На объекте оцениваем основание, объём и состав работ. Сразу называем стоимость — без скрытых доплат и неожиданных пунктов.</p><ul><li>Бесплатный выезд в течение 24 часов</li><li>Расчёт работ отдельно или с материалом</li><li>Условия фиксируются до начала работ</li></ul><a className="button" href="#contact">Получить расчёт<span>↓</span></a></div></div></section>
    <section className="materials section container"><p className="eyebrow">Проверенные смеси</p><div className="section-heading"><h2>Материалы, соответствующие<br/>условиям объекта.</h2><p>Подбираем состав по основанию, влажности помещения и дальнейшей отделке. Организуем доставку и привозим материал на объект.</p></div><div className="material-grid">{materialGroups.map(([title, ...items]) => <article key={title}><p>{title}</p>{items.map((item) => <b key={item}>{item}</b>)}</article>)}</div><div className="material-carousel" role="region" aria-label="Материалы, с которыми работаем">{materialCards.map((material, index) => <article className="material-card" key={material.title}><div className="material-image"><img src={material.image} alt={material.alt} loading="lazy" /></div><div><div className="material-title"><span>{String(index + 1).padStart(2, "0")}</span><h3>{material.title}</h3></div><p>{material.text}</p></div></article>)}</div></section>
    <section className="portfolio section" id="portfolio"><div className="container"><p className="eyebrow">Реальные объекты</p><div className="section-heading"><h2>Работа<br />в деталях.</h2><p>Фотографии с частных объектов: подготовка основания, коммуникации и выполненная механизированная штукатурка.</p></div><figure className="portfolio-feature"><a href="#work-01" aria-label="Открыть главное фото"><img src={portfolio[0].src} alt={portfolio[0].alt} /><figcaption>Реальный объект · механизированная штукатурка <span>↗</span></figcaption></a></figure><div className="portfolio-carousel" role="region" aria-label="Галерея выполненных работ">{portfolio.slice(1).map((photo, index) => <figure className="portfolio-carousel-item" key={photo.src}><a href={`#work-${String(index + 2).padStart(2, "0")}`} aria-label={`Открыть фото ${index + 2}`}><img src={photo.src} alt={photo.alt} loading="lazy" /><span>{String(index + 2).padStart(2, "0")}</span></a></figure>)}</div><p className="carousel-hint">Нажмите на фото, чтобы открыть его <span>↗</span></p><div className="portfolio-cta"><p>Хотите увидеть похожий объект или прислать план?</p><a className="button" href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Написать в Telegram<span>↗</span></a></div></div><div className="portfolio-lightboxes" aria-label="Просмотр галереи">{portfolio.map((photo, index) => <figure className="portfolio-lightbox" id={`work-${String(index + 1).padStart(2, "0")}`} key={photo.src}><a className="lightbox-close" href="#portfolio" aria-label="Закрыть просмотр">×</a><img src={photo.src} alt={photo.alt} /><figcaption><a href={`#work-${String((index + portfolio.length - 1) % portfolio.length + 1).padStart(2, "0")}`} aria-label="Предыдущее фото">←</a><span>{String(index + 1).padStart(2, "0")} / {String(portfolio.length).padStart(2, "0")}</span><a href={`#work-${String((index + 1) % portfolio.length + 1).padStart(2, "0")}`} aria-label="Следующее фото">→</a></figcaption></figure>)}</div></section>
    <section className="principles" id="process"><div className="container principles-grid"><p className="eyebrow">Как всё происходит</p><div><h2>Понятно<br />с первого звонка.</h2><div className="principle-items"><p><b>01 · Фото или план</b><span>Пишите в Telegram или звоните. Можно прислать план, фото помещений или описать задачу.</span></p><p><b>02 · Замер и смета</b><span>Бесплатно выезжаем в течение 24 часов, уточняем объём и сразу считаем стоимость.</span></p><p><b>03 · Договор и работы</b><span>Согласовываем условия, организуем доставку материалов и приступаем к работе по договору подряда.</span></p></div></div></div></section>
    <section className="trust section container"><p className="eyebrow">Реальная репутация</p><div className="trust-card"><div><h2>Отзывы —<br />на Авито.</h2><p>У Евгения есть живые отзывы клиентов и портфолио с описаниями объектов. Для прозрачности открываем первоисточник, а не публикуем анонимные цитаты.</p></div><a className="button" href="https://www.avito.ru/engels/predlozheniya_uslug/mehanizirovannaya_shtukaturka_2039745536" target="_blank" rel="noreferrer">Смотреть на Авито<span>↗</span></a></div></section>
    <section className="faq section container" id="faq"><p className="eyebrow">Перед началом работ</p><div className="section-heading"><h2>Отвечаем<br />заранее.</h2><p>Коротко о том, что обычно важно обсудить до замера и старта работ.</p></div><div className="faq-list"><details open><summary>Какая минимальная площадь объекта?<span>+</span></summary><p>Работаем с объектами от 70 м². Для небольших или нестандартных задач лучше написать и обсудить условия отдельно.</p></details><details><summary>Когда происходит замер?<span>+</span></summary><p>Бесплатный замер и расчёт проводятся в течение 24 часов — в Энгельсе, Саратове и области.</p></details><details><summary>Сколько занимает работа?<span>+</span></summary><p>Средний срок на частном объекте — от 3 до 8 рабочих дней. Точный срок зависит от площади, подготовки и состава работ.</p></details><details><summary>Как проходит оплата материалов и работ?<span>+</span></summary><p>Материалы организуем и доставляем сами: сначала они поступают на объект, затем вы их оплачиваете. Стоимость работ фиксируем в смете на замере и договоре.</p></details><details><summary>Есть ли договор и гарантия?<span>+</span></summary><p>Работаем по договору подряда с физическими и юридическими лицами. Гарантия на выполненные работы — до 1 года по договорённости.</p></details></div></section>
    <section className="contact section container" id="contact"><div><p className="eyebrow">Рассчитаем ваш объект</p><h2>Покажите<br />план или фото.</h2><p className="contact-note">Напишите в Telegram: можно отправить план, фото помещения или просто описать задачу. Евгений ответит лично.</p><p className="contact-hours">Звонки принимаем ежедневно с 8:00 до 22:00.</p></div><div className="contact-card"><p>Связаться с мастером</p><h3>Евгений</h3><a className="phone" href="tel:+79878017549">+7 987 801-75-49</a><a className="button contact-button" href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Написать в Telegram<span>↗</span></a><small>Механизированная штукатурка и стяжка пола<br />Энгельс · Саратов · область</small></div></section>
    <footer className="footer container"><a className="brand" href="#top">РОВНАЯ ОСНОВА<span>•</span></a><p>Механизированная штукатурка и стяжка пола</p><a href="tel:+79878017549">Позвонить</a></footer>
    <aside className="mobile-contact" aria-label="Быстрая связь"><a href="tel:+79878017549">Позвонить</a><a href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Telegram ↗</a></aside>
  </main>;
}
