const services = [
  { number: "01", title: "Механизированная штукатурка", text: "Подготавливаем стены и откосы частного дома под дальнейшую отделку. Учитываем особенности основания и будущую финишную отделку.", image: "https://cdn.prod.website-files.com/641944630ef1ae6464010259/66c5dc637ca9aff3e46038d2_650bf34d7b264729a5b20e95_Selecting%2520the%2520perfect%2520color%2520scheme.webp" },
  { number: "02", title: "Механизированная стяжка пола", text: "Создаём ровное и прочное основание для пола в доме — под плитку, ламинат, кварцвинил и другие покрытия.", image: "https://majostavby.sk/wp-content/uploads/2021/06/20200507_153211-scaled.jpg" },
];

export default function Home() {
  return <main>
    <section className="hero" id="top">
      <nav className="nav container" aria-label="Основная навигация"><a className="brand" href="#top" aria-label="Ровная Основа — на главную">РОВНАЯ<br />ОСНОВА<span>•</span></a><div className="nav-links"><a href="#services">Услуги</a><a href="#advantages">Преимущества</a><a href="#process">Как работаем</a><a href="#faq">Вопросы</a></div><a className="nav-cta" href="#contact">Рассчитать объект</a><details className="nav-menu"><summary aria-label="Открыть меню"><i /><i /><i /></summary><div><a href="#services">Услуги</a><a href="#advantages">Преимущества</a><a href="#process">Как работаем</a><a href="#faq">Вопросы</a><a href="#contact">Связаться</a></div></details></nav>
      <div className="hero-grid container"><div className="hero-copy"><p className="eyebrow">Частные дома · Коттеджи</p><h1>Ровный дом<br />с первого слоя.</h1><p className="lead">Механизированная штукатурка и стяжка пола для частных домов. Делаем основу ремонта, на которой можно уверенно продолжать отделку.</p><div className="hero-actions"><a className="button" href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Написать Евгению <span>↗</span></a><a className="text-link" href="tel:+79878017549">+7 987 801-75-49</a></div></div><div className="hero-visual"><img src="https://www.daibau.rs/showfile.php?id=433810" alt="Стяжка пола в строящемся частном доме" /><p className="visual-label">Частные дома · Всё для ровной основы</p></div></div>
      <div className="hero-foot container"><span>ЧЕСТНЫЕ УСЛОВИЯ ПО МАТЕРИАЛАМ</span><span>ОСТАЛЬНОЕ — ПО ЗАПРОСУ</span></div>
    </section>
    <section className="services section container" id="services"><p className="eyebrow">Основные услуги</p><div className="section-heading"><h2>Делаем основу<br />дома правильно.</h2><p>Фокусируемся на двух главных этапах. Другие строительные работы выполняем по запросу.</p></div><div className="service-grid">{services.map((service) => <article className="service" key={service.number}><img src={service.image} alt={service.title} /><div className="service-info"><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.text}</p></div></article>)}</div></section>
    <section className="terms section" id="advantages"><div className="container"><p className="eyebrow">Честные условия</p><div className="terms-heading"><h2>Сначала материал<br />на объекте. Потом оплата.</h2><p>Материалы заказываются под согласованный объём работ. Вы оплачиваете их только после фактической доставки на объект — не переводите деньги за материал заранее.</p></div><div className="terms-grid"><article><span>В ТЕЧЕНИЕ 24 ЧАСОВ</span><h3>Бесплатный замер</h3><p>Согласуем удобное время, приедем на объект и уточним объём работ.</p></article><article className="featured"><span>ГЛАВНОЕ УСЛОВИЕ</span><h3>Материалы уже на объекте</h3><p>Сначала вы видите доставленный материал. Только после этого оплачиваете его стоимость.</p></article><article><span>ПРОЗРАЧНО</span><h3>Без аванса за материал</h3><p>Никаких переводов за ещё не доставленные смеси и расходники.</p></article></div></div></section>
    <section className="principles" id="process"><div className="container principles-grid"><p className="eyebrow">Как всё происходит</p><div><h2>Понятно<br />с первого звонка.</h2><div className="principle-items"><p><b>01 · Обсуждаем дом</b><span>Пишите в Telegram или звоните. Уточняем задачу и исходные данные.</span></p><p><b>02 · Согласовываем работы</b><span>Определяем объём, последовательность и материалы для конкретного дома.</span></p><p><b>03 · Доставка → оплата → работы</b><span>Материалы поступают на объект, вы оплачиваете их и мы приступаем к работе.</span></p></div></div></div></section>
    <section className="faq section container" id="faq"><p className="eyebrow">Перед началом работ</p><div className="section-heading"><h2>Отвечаем<br />заранее.</h2><p>Коротко о том, что обычно важно обсудить до замера и старта работ.</p></div><div className="faq-list"><details open><summary>Что прислать для первого расчёта?<span>+</span></summary><p>Достаточно плана дома, фотографий помещений или описания задачи. Так будет проще сориентироваться перед замером.</p></details><details><summary>Когда происходит замер?<span>+</span></summary><p>Выезд на объект согласуем в удобное время. Бесплатный замер проводится в течение 24 часов.</p></details><details><summary>Когда оплачиваются материалы?<span>+</span></summary><p>Материалы сначала поступают на объект. Вы видите доставку и только после этого оплачиваете их стоимость.</p></details><details><summary>Можно обсудить другие работы по дому?<span>+</span></summary><p>Да. Основные направления — штукатурка и стяжка, а дополнительные строительные задачи можно обсудить отдельно.</p></details></div></section>
    <section className="contact section container" id="contact"><div><p className="eyebrow">Рассчитаем ваш объект</p><h2>Покажите<br />план или фото.</h2><p className="contact-note">Напишите в Telegram: можно отправить план, фото помещения или просто описать задачу. Евгений ответит лично.</p></div><div className="contact-card"><p>Связаться с мастером</p><h3>Евгений</h3><a className="phone" href="tel:+79878017549">+7 987 801-75-49</a><a className="button" href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Написать в Telegram <span>↗</span></a><small>Механизированная штукатурка и стяжка пола</small></div></section>
    <footer className="footer container"><a className="brand" href="#top">РОВНАЯ ОСНОВА<span>•</span></a><p>Механизированная штукатурка и стяжка пола</p><a href="tel:+79878017549">Позвонить</a></footer>
    <aside className="mobile-contact" aria-label="Быстрая связь"><a href="tel:+79878017549">Позвонить</a><a href="https://t.me/Makao_O" target="_blank" rel="noreferrer">Telegram ↗</a></aside>
  </main>;
}
